from flask import Flask, jsonify, Response
import yaml

app = Flask(__name__)

@app.route("/")
def home():
    return "🌊 Offshore Intelligence API v2 is running and ready to serve data."

@app.route("/api/backlog")
def backlog():
    data = [
        {"project": "Hollandse Kust West", "contractor": "Van Oord", "foundation_type": "Monopile", "status": "planned", "region": "North Sea"},
        {"project": "Dogger Bank", "contractor": "SSE Renewables", "foundation_type": "Jacket", "status": "under construction", "region": "UK North Sea"}
    ]
    return jsonify(data)

@app.route("/api/news")
def news():
    data = {
        "source": "offshorewind.biz",
        "articles": [
            {"title": "Van Oord wins new offshore wind contract", "link": "https://www.offshorewind.biz/article1", "published": "2025-10-22T10:00:00Z"},
            {"title": "Siemens Gamesa expands offshore turbine capacity", "link": "https://www.offshorewind.biz/article2", "published": "2025-10-21T08:00:00Z"}
        ]
    }
    return jsonify(data)

@app.route("/openapi.yaml")
def openapi():
    with open("openapi.yaml", "r") as f:
        openapi_text = f.read()
    return Response(openapi_text, mimetype="application/yaml")

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10000)
